version: '3.8'
services:
  smartcard:
    image: ers-smartcard:latest
    ports:
      - '8443:8443'
      - '8080:80'
    environment:
      - SERVER_PORT=8443
      - CLIENT_SECRET
      - ERS_SESSIONHANDOVERENDPOINT
      - CLIENT_ID
      - SERVER_SSL_CERTIFICATEPRIVATEKEY
      - REDIRECT_URI=https://localhost:8443/login/oauth2/code/cis2
      - OAUTH_ENDPOINT=https://int.api.service.nhs.uk/oauth2-mock
      - SERVER_HTTPPORT=80
      - SERVER_SSL_CERTIFICATE
      - ODS_CODE
      - SERVER_ENABLETLS=true
  iris:
    image: ers-tie:latest
    ports:
      - '1972:1972'
      - '52773:52773'
      - '9985:9985'
    volumes:
      - irisconfig:/dur
    cap_add:
      - IPC_LOCK
    environment:
#      - ISC_DATA_DIRECTORY=/dur/iris_conf.d
#      - ISC_CPF_MERGE_FILE=/dur/merge/merge.cpf
      - IRIS_USERNAME=ersuser
      - IRIS_PASSWORD=password
      - IRIS_NAMESPACE=ERS
  sql:
    image: ers-sql:latest
    ports: 
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password123!
  ui:
    image: ers-ui:latest
    ports: 
      - '3000:3000'
  api:
    image: ers-api:latest
    ports:
      - '7204:80'
volumes:
  irisconfig: