
INSERT INTO ersRefReq_Details (RefReq_UniqueID,RefReq_NHSNo,RefReq_UBRN,RefReq_TrustNACS,Appt_StDttm,Appt_EndDttm,RefReq_Specialty,RefReq_Status,RefReq_intent,RefReq_Priority,RefReq_Noofdocs,RefReq_FullURL,rec_UpdatedBy,rec_insertedBy) VALUES ('000000070000','9912003888','000000070000','RFR','','','','NOT_BOOKED','plan','ROUTINE',1,'https://sandbox.api.service.nhs.uk/referrals/FHIR/STU3/ReferralRequest/000000070000','TIE','TIE');
INSERT INTO ersdoc_attachments (Attach_ID,RefDoc_srlno,RefDoc_UniqueID,RefDocStatus,Attach_InsertedBy,Attach_ContentType,Attach_URL,Attach_Size,Attach_Title,Attach_CrtdDTTM,DocDownloadURL,DocLocationURI,rec_Updated,rec_UpdatedBy,rec_insertedBy) VALUES ('80000','1','000000070000','current','021600556514','application/pdf','att-70000-80000','6','referralletter.pdf','2021-06-11','https://sandbox.api.service.nhs.uk/referrals/FHIR/STU3/Binary/att-70000-80000','trustfileloc/att-70000-80000',GETDATE(),'TIE','TIE');


INSERT INTO ersRefReq_Details (RefReq_UniqueID,RefReq_NHSNo,RefReq_UBRN,RefReq_TrustNACS,Appt_StDttm,Appt_EndDttm,RefReq_Specialty,RefReq_Status,RefReq_intent,RefReq_Priority,RefReq_Noofdocs,RefReq_FullURL,rec_UpdatedBy,rec_insertedBy) VALUES ('000000070004','9912003888','000000070004','RFR','','','CARDIOLOGY','TRIAGED_PROVIDER_TO_ACTION','plan','TWO_WEEK_WAIT',1,'https://sandbox.api.service.nhs.uk/referrals/FHIR/STU3/ReferralRequest/000000070004','TIE','TIE');
INSERT INTO ersdoc_attachments (Attach_ID,RefDoc_srlno,RefDoc_UniqueID,RefDocStatus,Attach_InsertedBy,Attach_ContentType,Attach_URL,Attach_Size,Attach_Title,Attach_CrtdDTTM,DocDownloadURL,DocLocationURI,rec_Updated,rec_UpdatedBy,rec_insertedBy) VALUES ('80002','1','000000070004','current','021600556514','image/png','att-70004-80002','6','triage.png','2021-06-11','https://sandbox.api.service.nhs.uk/referrals/FHIR/STU3/Binary/att-70004-80002','trustfileloc/att-70004-80002',GETDATE(),'TIE','TIE');


INSERT INTO ersRefReq_Details (RefReq_UniqueID,RefReq_NHSNo,RefReq_UBRN,RefReq_TrustNACS,Appt_StDttm,Appt_EndDttm,RefReq_Specialty,RefReq_Status,RefReq_intent,RefReq_Priority,RefReq_Noofdocs,RefReq_FullURL,rec_UpdatedBy,rec_insertedBy) VALUES ('000000070002','9912003888','000000070002','RFR','2021-07-05T10:00:00.000Z','2021-07-05T10:00:00.000Z','CARDIOLOGY','BOOKED','plan','ROUTINE',1,'https://sandbox.api.service.nhs.uk/referrals/FHIR/STU3/ReferralRequest/000000070002','TIE','TIE');
INSERT INTO ersdoc_attachments (Attach_ID,RefDoc_srlno,RefDoc_UniqueID,RefDocStatus,Attach_InsertedBy,Attach_ContentType,Attach_URL,Attach_Size,Attach_Title,Attach_CrtdDTTM,DocDownloadURL,DocLocationURI,rec_Updated,rec_UpdatedBy,rec_insertedBy) VALUES ('80000','1','000000070002','current','021600556514','application/pdf','att-70002-80000','6','referralletter.pdf','2021-06-11','https://sandbox.api.service.nhs.uk/referrals/FHIR/STU3/Binary/att-70002-80000','trustfileloc/att-70002-80000',GETDATE(),'TIE','TIE');

INSERT INTO patients (pat_ubrn,pat_mrn,pat_nhs,pat_familyName,pat_givenName,pat_sex,pat_dob,pat_addressOne,pat_addressTwo,pat_addressThree,pat_PostCode,pat_contactNumber,rec_Updated,rec_UpdatedBy) VALUES ('000000070002', '00000000', '9912003888', 'Cryer', 'Beth', 'F', '2001-02-19', 'Union Mills', null, null, 'LS64JU', '07709345281', GETDATE(), 'TIE');
INSERT INTO patients (pat_ubrn,pat_mrn,pat_nhs,pat_familyName,pat_givenName,pat_sex,pat_dob,pat_addressOne,pat_addressTwo,pat_addressThree,pat_PostCode,pat_contactNumber,rec_Updated,rec_UpdatedBy) VALUES ('000000070000', '00000000', '9912003888', 'Cryer', 'Beth', 'F', '2001-02-19', 'Union Mills', null, null, 'LS64JU', '07709345281', GETDATE(), 'TIE');
INSERT INTO patients (pat_ubrn,pat_mrn,pat_nhs,pat_familyName,pat_givenName,pat_sex,pat_dob,pat_addressOne,pat_addressTwo,pat_addressThree,pat_PostCode,pat_contactNumber,rec_Updated,rec_UpdatedBy) VALUES ('000000070004', '00000000', '9912003888', 'Cryer', 'Beth', 'F', '2001-02-19', 'Union Mills', null, null, 'LS64JU', '07709345281', GETDATE(), 'TIE');

INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ERSDL-SUCC','Document Downloaded from eRS to Trust Network successfully.','Awaiting Upload to EPR',1,'0','3#4','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ERSDL-FAIL','Document Download failed.','Failed to Download',2,'0','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ULEPR-SUCC','Uploaded to EPR','Uploaded to EPR',3,'1','5#6','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ULEPR-FAIL','Technical issue in uploading EPR','Failed to upload to EPR',4,'1','1','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-QCEPR-SUCC','Quality Check Success & Document in EPR','Quality Check Success',5,'3','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-QCEPR-FAIL','Quality Check Failed','Quality Check Failed',6,'3','3','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);

INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ERSDL-SUCC','Attached Documents downloaded successfully.','Awaiting Upload to EPR',7,'0','9#10','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ERSDL-FAIL','Attached Documents partially downloaded or missing.','Attachment Downloads Incomplete',8,'0','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ULEPR-SUCC','Uploaded to EPR','Uploaded to EPR',9,'7','11#12','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ULEPR-FAIL','Technical issue in uploading EPR','Failed to upload to EPR',10,'7','7','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-QCEPR-SUCC','Quality Check Success & Document in EPR','Quality Check Success',11,'9','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-QCEPR-FAIL','Quality Check Failed','Quality Check Failed',12,'9','9','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);