server:
  http-port: ${HTTP_PORT}
  port: ${HTTPS_PORT}
  enable-tls: false
spring:
  security:
    oauth2:
      client:
        registration:
          cis2:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
        provider:
          cis2:
            authorization-uri: ${OAUTH_ENDPOINT}/authorize
            token-uri: ${OAUTH_ENDPOINT}/token
            user-info-uri: ${OAUTH_ENDPOINT}/userinfo
            userNameAttribute: name
logging.level:
  com.answerdigital.ers: DEBUG
  root: INFO
debug: true