INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ERSDL-SUCC','Document Downloaded from eRS to Trust Network successfully.','Awaiting Upload to EPR',1,'0','3#4','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ERSDL-FAIL','Document Download failed.','Failed to Download',2,'0','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ULEPR-SUCC','Uploaded to EPR','Uploaded to EPR',3,'1','5#6','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-ULEPR-FAIL','Technical issue in uploading EPR','Failed to upload to EPR',4,'1','1','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-QCEPR-SUCC','Quality Check Success & Document in EPR','Quality Check Success',5,'3','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('D-QCEPR-FAIL','Quality Check Failed','Quality Check Failed',6,'3','3','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);

INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ERSDL-SUCC','Attached Documents downloaded successfully.','Awaiting Upload to EPR',7,'0','9#10','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ERSDL-FAIL','Attached Documents partially downloaded or missing.','Attachment Downloads Incomplete',8,'0','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ULEPR-SUCC','Uploaded to EPR','Uploaded to EPR',9,'7','11#12','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-ULEPR-FAIL','Technical issue in uploading EPR','Failed to upload to EPR',10,'7','7','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-QCEPR-SUCC','Quality Check Success & Document in EPR','Quality Check Success',11,'9','0','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);
INSERT INTO wfs_master(wfsm_code, wfsm_description, wfsm_displayvalue, wfsm_hierarchy, wfsm_prevhierarchy, wfsm_nexthierarchy, rec_status, rec_updated, rec_updatedby, rec_inserted, rec_insertedby,rec_PurgeDays) VALUES('R-QCEPR-FAIL','Quality Check Failed','Quality Check Failed',12,'9','9','A', GETDATE(), 'Admin', GETDATE(), 'Admin',0);

